config/routes.rb
Onboard::Application.routes.draw do


  # the urls we need for omniauth

  get "auth/:provider/callback" => "social_logins#create"

  get "auth/:provider/failure" => "social_logins#failure"

  

  

  # has to match with your controllers
  # hook up urls with rooms controller

  #  orders are insdie beacuse we want to place an order
  resources :rooms do
    resources :orders, only: [:new, :create]

  end

  # my list of orders dont have to be on a room

  resources :orders, only: [:index, :show]


  # sign up our users to the site

  resources :users


  # log in and log out of our site
  # its a singular resource because we can only do one session

  resource :session

  # go to the home page
  root "rooms#index"

  


 
end

app/models/order.rb
class Order < ActiveRecord::Base


	# associataions 

	belongs_to :user

	belongs_to :room




end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  # before everything maeksue logged in

  before_action :make_sure_logged_in




	  def index

	  	@orders = current_user.orders.all


	  end

	  def show

	  	@order = current_user.orders.find(params[:id])


	  end

	  def new

	  	#  letes find the room from our routes

	  	@room = Room.find(params[:room_id])

	  	@order = @room.orders.new

	  	@order.user = current_user


	  end



	  def create

	  	#  submited the form and lets save the order

	  	@room = Room.find(params[:room_id])

	  	@order = @room.orders.new(order_params)

	  	@order.user = current_user


	  	if @order.save

	  		# we want charge stripe with the token
	  		Stripe::Charge.create(card: @order.stripe_token, 
	  				description: "room onboard", amount: (@room.price * 100).to_i,
	  				currency: "gbp")


	  		flash[:success] = " you've order this room"
	  		redirect_to room_path(@room)


	  	else

	  		render "new"

	  	end


	  end 



	  private 

	  def order_params

	  	params.require(:order).permit(:stripe_token)

	  end






end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<h1> Your orders </h1>

<ul>
	
<% @orders.each do |order| %>

	<li>
		
	<%= link_to "order number #{order.id}", order_path(order) %>

	<%= order.room.title %>

	</li>

<% end %>







</ul>

app/views/orders/new.html.erb
<%= simple_form_for [@room, @order] do |form| %>

  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
</form>

<% end %>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('<%= STRIPE_KEY%>');
  // ...



 jQuery(function($) {
  $('#new_order').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});

 var stripeResponseHandler = function(status, response) {
  var $form = $('#new_order');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // token contains id, last4, and card type
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};




</script>

app/views/orders/show.html.erb
<h1>Orders#show</h1>

<p> Address is : <%= @order.room.address%></p>

<p> user is : <%= @order.room.user%></p>

<p> title is : <%= @order.room.title%></p>


<p>test </p>