config/routes.rb
Onboard::Application.routes.draw do


  # the urls we need for omniauth

  get "auth/:provider/callback" => "social_logins#create"

  get "auth/:provider/failure" => "social_logins#failure"

  

  

  # has to match with your controllers
  # hook up urls with rooms controller

  #  orders are insdie beacuse we want to place an order
  resources :rooms do
    resources :orders, only: [:new, :create]

  end

  # my list of orders dont have to be on a room

  resources :orders, only: [:index, :show]


  # sign up our users to the site

  resources :users


  # log in and log out of our site
  # its a singular resource because we can only do one session

  resource :session

  # go to the home page
  root "rooms#index"

  


 
end

app/models/room.rb
class Room < ActiveRecord::Base


	# association - creates relationships between tables
	belongs_to :user
	has_many :orders

	# this is fron the rubygeocoder.org site

	geocoded_by :address
	after_validation :geocode

	#  add in paperclip to save images
	# the hash after 960x300 means we crop the image
	# if we wanted it to be a certain width: "500x"
	# if we wanted it to be a certain height: "x500"

	has_attached_file :image, styles: { large: "960x300#", thumbnail: "50x50#" }

	 # images are cropped ..... 





	# validations

	validates :title, presence: true

	validates :address, presence: true
	
	# more than 50 pence

	validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.5}


	





end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController



	#  before quite a few of the actions below
	#  makesure we're logged in

	before_action :make_sure_logged_in, except: [:index, :show]
	  


	  def index

	  	if params[:location].present?
	  		@rooms = Room.near(params[:location])
	  	else
	  		@rooms = Room.near("London")
	  	end
	  	# room.near("london") , will only show those near london


	  end

	  

	  def show
	  		# find room in database
	  		@room = Room.find(params[:id])
	  


	  end

	  



	  def new

	  	@room = current_user.rooms.new
	  

	  end


	
	  def create

		  	@room = current_user.rooms.new(room_params)

		  	if @room.save

		  		flash[:success] = "You've added a room"

		  		redirect_to room_path(@room)



	  		else

	  			render "new"


	  		end

		
	  end  



	  def edit

	  	@room = current_user.rooms.find(params[:id])
	  

	  end



	  def update

	  	@room = current_user.rooms.find(params[:id])

	  	if @room.update(room_params)

	  		flash[:success] = "Your room has been updated"
	  		redirect_to room_path(@room)

	  	else

	  		render "edit"

	  	end


	  end




	  def destroy

	  	@room = Room.find(params[:id])

	  	@room.destroy

	  	flash[:success] = "your room has been deleted"

	  	redirect_to room_path


	  end


	  private 

	  #  stop edits.......

	  def room_params
	  	
	  	# shortcut for whitelisting form data

	  	params.require(:room).permit(:title, :address, :description, :max_guests, :bedrooms, :price, :image)

	  	# add variables that users can add in , like images


	  end



end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>

<%= form.input :title %>
<%= form.input :address %>
<%= form.input :description %>
<%= form.input :image %>
<%= form.input :bedrooms %>
<%= form.input :max_guests %>
<%= form.input :price %>

<%= form.button :submit %>

<% end %>

app/views/rooms/edit.html.erb
<%= render "form" %>

app/views/rooms/index.html.erb
<% @rooms.each do |room| %>

	

	<div class="room">
		<%= link_to room.title, room_path(room) %>

		<!-- if room.image is present, else show message -->
		<%= image_tag room.image(:large) %>

	</div>


<% end %>


<%= link_to "add a room", new_room_path %>

app/views/rooms/new.html.erb
<%= render "form" %>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<!-- <p>Find me in app/views/rooms/show.html.erb</p>
 -->

<h2><%= @room.title%></h2>

<%= image_tag @room.image(:large) %>



<p><%= @room.address %></p>

<p><%= @room.latitude %> <%= @room.longitude %></p>


<div class="map" data-lat="<%= @room.latitude %>" data-lng="<%= @room.longitude %>"></div>

<!-- show the map below the  -->


<% if current_user.present? %>
<!-- check if users is logged in, only show the below if they are -->
<!-- if you are logged in, it will show book room -->

<div class="actions">

	<%= link_to "Book Room", new_room_order_path(@room), class: "button"%>

		<% if current_user == @room.user %>
		<%= link_to "edit", edit_room_path(@room), class: "button" %>

		<%= link_to "delete", room_path(@room), method: :delete, class: "button", confirm: "are you sure?"%>
	
		<% end %>

<!-- you wont see the room if you dont own it,  -->

</div>

<% end %>