config/routes.rb
Onboard::Application.routes.draw do


  # the urls we need for omniauth

  get "auth/:provider/callback" => "social_logins#create"

  get "auth/:provider/failure" => "social_logins#failure"

  

  

  # has to match with your controllers
  # hook up urls with rooms controller

  #  orders are insdie beacuse we want to place an order
  resources :rooms do
    resources :orders, only: [:new, :create]

  end

  # my list of orders dont have to be on a room

  resources :orders, only: [:index, :show]


  # sign up our users to the site

  resources :users


  # log in and log out of our site
  # its a singular resource because we can only do one session

  resource :session

  # go to the home page
  root "rooms#index"

  


 
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Onboard</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header class="row">
    <h1 class="two columns">
      <%= link_to(root_path) do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </h1>

    <form action="<%= root_path %>" class="three columns">
      <input type="text" name="location">
    </form>

    <nav class="seven columns">
    

      <!-- I am signed up as user number: <%= session[:user_id]%> -->

      <% if current_user.present? %>
      <strong><%= current_user.username%></strong>

      <%= link_to "Dashboard", "#" %>
      <%= link_to "Add a room", new_room_path %>
      <%= link_to "Orders", orders_path %>
      <%= link_to "Log out", session_path, method: :delete %>


      <% else %>
      
      <!-- if there is not a current user show this  -->
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Sign in", new_session_path %>

      <% end %>
      
     
    </nav>
  </header>

  <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
  <% end %>

  <article class="row">
    <%= yield %>
  </article>

  <footer>
    <p>&copy; <%= Date.today.year %> Onboard Ltd</p>
  </footer>
</div>

</body>
</html>